// <auto-generated />
namespace PayrollSystem.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class yes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(yes));
        
        string IMigrationMetadata.Id
        {
            get { return "201307292247231_yes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
